# Base Image
FROM debian

# Labels
LABEL maintainer="Barış DEMİRCİ, <demirci.baris38@gmail.com"
LABEL version="1.0.0"
LABEL description="Slash command based level bot for Discord"

# Update and download linux dependencies
RUN apt-get update && apt-get install -y curl software-properties-common git make python gcc g++

# Add NodeJS PPA
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

# Install NodeJS
RUN apt-get install -y nodejs && apt-get clean

# Set environment variables
ENV CLIENT_ID=
ENV TOKEN=
ENV MONGODB_URI=
ENV PORT=8080

# Reserve ports
EXPOSE 8080

# Set workdir
WORKDIR /app

# Copy required files
ADD tsconfig.json . 
ADD package.json .
ADD src src

# Download dependencies
RUN npm i

# Build bot
RUN npm run build

# Remove useless folders
RUN rm -r src

# Set container command
CMD [ "npm", "run", "start:prod" ]
